from __future__ import annotations

from datetime import date

from it_doc_builder.models import DocumentTypeDefinition


DOCUMENT_TYPES: list[DocumentTypeDefinition] = [
    DocumentTypeDefinition(
        key="general-work-report",
        name="General Work Report",
        category="Operational",
        type_code="GWR",
        subtype_code="001",
        description="A broad summary of IT work completed for a project, ticket set, or service window.",
        common_triggers=["Weekly summary", "Project milestone", "Service desk wrap-up"],
        required_sections=["Executive Summary", "Work Performed", "Open Items", "Recommended Follow-up"],
    ),
    DocumentTypeDefinition(
        key="change-order",
        name="Change Order",
        category="Change Management",
        type_code="CHO",
        subtype_code="002",
        description="Formal documentation for planned infrastructure or service changes requiring approvals and rollback notes.",
        common_triggers=["Firewall changes", "Server reconfiguration", "Production release"],
        required_sections=["Change Summary", "Business Justification", "Implementation Plan", "Rollback Plan", "Approval Status"],
    ),
    DocumentTypeDefinition(
        key="network-update",
        name="Network Update",
        category="Network",
        type_code="NET",
        subtype_code="003",
        description="Captures switch, routing, wireless, VLAN, ISP, and cabling changes affecting network operations.",
        common_triggers=["VLAN updates", "Switch replacement", "WAN failover changes"],
        required_sections=["Scope of Change", "Network Components Affected", "Validation Results", "Risks and Dependencies"],
    ),
    DocumentTypeDefinition(
        key="incident-report",
        name="Incident Report",
        category="Operations",
        type_code="INC",
        subtype_code="004",
        description="Records an outage, service degradation, or support incident with cause, response, and resolution.",
        common_triggers=["Email outage", "Authentication failure", "Major ticket escalation"],
        required_sections=["Incident Summary", "Timeline", "Impact", "Root Cause", "Corrective Actions"],
    ),
    DocumentTypeDefinition(
        key="maintenance-window",
        name="Maintenance Window Summary",
        category="Operations",
        type_code="MWN",
        subtype_code="005",
        description="Summarizes after-hours or planned maintenance work across one or more systems.",
        common_triggers=["Patch weekend", "Storage maintenance", "Hypervisor maintenance"],
        required_sections=["Maintenance Objectives", "Tasks Completed", "Validation", "Outstanding Issues"],
    ),
    DocumentTypeDefinition(
        key="system-upgrade",
        name="System Upgrade Report",
        category="Infrastructure",
        type_code="SUP",
        subtype_code="006",
        description="Tracks software, firmware, or platform upgrades with prechecks and post-upgrade status.",
        common_triggers=["OS upgrade", "Application version upgrade", "Firmware refresh"],
        required_sections=["Upgrade Scope", "Pre-Upgrade Checks", "Execution Summary", "Post-Upgrade Validation"],
    ),
    DocumentTypeDefinition(
        key="workstation-deployment",
        name="Workstation Deployment",
        category="Endpoint",
        type_code="WSD",
        subtype_code="007",
        description="Documents endpoint builds, replacements, user migration, and handoff status.",
        common_triggers=["New hire setup", "Laptop refresh", "Department rollout"],
        required_sections=["Deployment Scope", "Assets Provisioned", "User Impact", "Completion Status"],
    ),
    DocumentTypeDefinition(
        key="access-change",
        name="Access Change Record",
        category="Identity",
        type_code="ACR",
        subtype_code="008",
        description="Records permission changes, onboarding, offboarding, or privileged access updates.",
        common_triggers=["Role changes", "Terminations", "Admin group updates"],
        required_sections=["Requested Change", "Systems Affected", "Approvals", "Verification"],
    ),
    DocumentTypeDefinition(
        key="security-finding",
        name="Security Finding",
        category="Security",
        type_code="SCF",
        subtype_code="009",
        description="Formal write-up for vulnerabilities, suspicious activity, or security control gaps.",
        common_triggers=["Vulnerability scan result", "Phishing incident", "Audit exception"],
        required_sections=["Finding Summary", "Risk Rating", "Affected Assets", "Mitigation Plan", "Owner and Due Date"],
    ),
    DocumentTypeDefinition(
        key="backup-recovery",
        name="Backup or Recovery Report",
        category="Resilience",
        type_code="BKR",
        subtype_code="010",
        description="Documents restore tests, backup issues, or disaster recovery actions and outcomes.",
        common_triggers=["Restore validation", "Recovery operation", "Backup job failures"],
        required_sections=["Scenario", "Systems Protected", "Recovery Steps", "Results", "Gaps Identified"],
    ),
    DocumentTypeDefinition(
        key="vendor-service-update",
        name="Vendor Service Update",
        category="Service Management",
        type_code="VSU",
        subtype_code="011",
        description="Summarizes provider-led changes, outages, deliverables, or implementation milestones.",
        common_triggers=["ISP cutover", "SaaS change notice", "Consultant delivery"],
        required_sections=["Vendor Activity", "Customer Impact", "Dependencies", "Next Actions"],
    ),
    DocumentTypeDefinition(
        key="asset-lifecycle",
        name="Asset Lifecycle Record",
        category="Asset Management",
        type_code="ALR",
        subtype_code="012",
        description="Tracks procurement, installation, reassignment, retirement, or disposal of equipment.",
        common_triggers=["Device retirement", "Inventory adjustments", "Warranty replacement"],
        required_sections=["Asset Summary", "Lifecycle Event", "Chain of Custody", "Record Updates"],
    ),
    DocumentTypeDefinition(
        key="project-handoff",
        name="Project Handoff",
        category="Project Delivery",
        type_code="PHO",
        subtype_code="013",
        description="Transfers a delivered solution into operations with support details and unresolved items.",
        common_triggers=["Go-live handoff", "Implementation closeout", "Operational transition"],
        required_sections=["Delivered Scope", "Operational Notes", "Known Issues", "Support Model"],
    ),
    DocumentTypeDefinition(
        key="executive-summary",
        name="Executive Summary Brief",
        category="Business Reporting",
        type_code="EXE",
        subtype_code="101",
        description="Leadership-focused summary of initiative status, outcomes, blockers, and decisions required.",
        common_triggers=["Steering committee update", "Quarterly review", "Executive checkpoint"],
        required_sections=["Business Context", "Current Status", "Risks", "Decisions Needed", "Next Milestones"],
    ),
    DocumentTypeDefinition(
        key="kpi-status-report",
        name="KPI Status Report",
        category="Business Reporting",
        type_code="KPI",
        subtype_code="102",
        description="Tracks performance metrics against target with commentary on trends and corrective actions.",
        common_triggers=["Monthly dashboard", "SLA review", "Performance reporting"],
        required_sections=["KPI Snapshot", "Target vs Actual", "Variance Analysis", "Corrective Actions"],
    ),
    DocumentTypeDefinition(
        key="financial-impact-summary",
        name="Financial Impact Summary",
        category="Business Reporting",
        type_code="FIN",
        subtype_code="103",
        description="Summarizes spend, savings, budget variance, and forecast impact for IT initiatives.",
        common_triggers=["Budget review", "Cost optimization update", "Funding request support"],
        required_sections=["Cost Summary", "Budget Variance", "Business Impact", "Forecast"],
    ),
    DocumentTypeDefinition(
        key="risk-register-update",
        name="Risk Register Update",
        category="Business Reporting",
        type_code="RSK",
        subtype_code="104",
        description="Structured update of open risks, severity shifts, owners, due dates, and mitigation status.",
        common_triggers=["Governance review", "Audit prep", "Program risk checkpoint"],
        required_sections=["Risk Overview", "Changes Since Last Update", "Top Risks", "Mitigation Progress", "Escalations"],
    ),
    DocumentTypeDefinition(
        key="project-status-brief",
        name="Project Status Brief",
        category="Business Reporting",
        type_code="PSB",
        subtype_code="105",
        description="Concise stakeholder update covering scope, schedule, dependencies, and upcoming deliverables.",
        common_triggers=["Weekly project update", "Client status update", "PMO reporting"],
        required_sections=["Scope Status", "Schedule Status", "Dependencies", "Issues and Blockers", "Upcoming Deliverables"],
    ),
    DocumentTypeDefinition(
        key="vulnerability-assessment",
        name="Vulnerability Assessment Report",
        category="Cybersecurity",
        type_code="VUL",
        subtype_code="201",
        description="Summarizes vulnerability scanning results, severity distribution, and remediation priorities.",
        common_triggers=["Monthly vulnerability scan", "External attack surface review", "Patch cycle planning"],
        required_sections=["Assessment Scope", "Findings Summary", "Severity Breakdown", "Remediation Plan", "Target Dates"],
    ),
    DocumentTypeDefinition(
        key="penetration-test-report",
        name="Penetration Test Report",
        category="Cybersecurity",
        type_code="PEN",
        subtype_code="202",
        description="Formal report of penetration testing methodology, exploitable findings, and recommendations.",
        common_triggers=["Annual pentest", "Pre-go-live security validation", "Regulatory testing requirement"],
        required_sections=["Test Scope", "Methodology", "Exploitable Findings", "Risk Ratings", "Recommendations"],
    ),
    DocumentTypeDefinition(
        key="threat-hunt-report",
        name="Threat Hunt Report",
        category="Cybersecurity",
        type_code="THR",
        subtype_code="203",
        description="Captures hypotheses, telemetry analysis, indicators, and conclusions from proactive threat hunting.",
        common_triggers=["SOC hunt cycle", "Suspicious behavior trend", "New threat intel advisory"],
        required_sections=["Hunt Hypothesis", "Data Sources", "Findings", "Indicators Observed", "Follow-up Actions"],
    ),
    DocumentTypeDefinition(
        key="incident-response-report",
        name="Incident Response Report",
        category="Cybersecurity",
        type_code="IRR",
        subtype_code="204",
        description="Detailed incident response record including detection, containment, eradication, and recovery.",
        common_triggers=["Malware outbreak", "Account compromise", "Data exfiltration alert"],
        required_sections=["Incident Overview", "Timeline", "Containment Actions", "Root Cause", "Lessons Learned"],
    ),
    DocumentTypeDefinition(
        key="security-control-validation",
        name="Security Control Validation",
        category="Cybersecurity",
        type_code="SCV",
        subtype_code="205",
        description="Evidence-based validation that technical and procedural controls are operating effectively.",
        common_triggers=["Audit preparation", "Post-hardening verification", "Control owner review"],
        required_sections=["Control Scope", "Validation Method", "Test Evidence", "Results", "Exceptions"],
    ),
    DocumentTypeDefinition(
        key="third-party-security-review",
        name="Third-Party Security Review",
        category="Cybersecurity",
        type_code="TPS",
        subtype_code="206",
        description="Security assessment of a vendor or SaaS provider with risk disposition and contract requirements.",
        common_triggers=["New vendor onboarding", "Renewal risk review", "Procurement due diligence"],
        required_sections=["Vendor Profile", "Security Posture", "Risk Findings", "Compensating Controls", "Decision"],
    ),
    DocumentTypeDefinition(
        key="phishing-campaign-analysis",
        name="Phishing Campaign Analysis",
        category="Cybersecurity",
        type_code="PHI",
        subtype_code="207",
        description="Analysis of phishing attempts, user impact, indicators, and response effectiveness.",
        common_triggers=["Reported phishing spike", "Mailbox compromise investigation", "Awareness campaign review"],
        required_sections=["Campaign Summary", "Indicators", "Impacted Users", "Response Actions", "Prevention Improvements"],
    ),
    DocumentTypeDefinition(
        key="acceptable-use-policy",
        name="Acceptable Use Policy",
        category="Governance",
        type_code="AUP",
        subtype_code="301",
        description="Defines acceptable use expectations for corporate systems, networks, applications, and data.",
        common_triggers=["Policy refresh", "Security awareness cycle", "Audit finding remediation"],
        required_sections=["Purpose and Scope", "Acceptable Use Rules", "Prohibited Activities", "Monitoring and Enforcement"],
    ),
    DocumentTypeDefinition(
        key="information-security-policy",
        name="Information Security Policy",
        category="Governance",
        type_code="ISP",
        subtype_code="302",
        description="Top-level policy establishing organizational information security principles and responsibilities.",
        common_triggers=["Annual policy review", "Compliance requirement", "Security program maturity update"],
        required_sections=["Policy Statement", "Roles and Responsibilities", "Control Domains", "Exceptions and Enforcement"],
    ),
    DocumentTypeDefinition(
        key="password-mfa-policy",
        name="Password and MFA Policy",
        category="Governance",
        type_code="PMF",
        subtype_code="303",
        description="Requirements for password strength, rotation, MFA enforcement, and secure authentication practices.",
        common_triggers=["Identity security initiative", "Audit recommendation", "Credential abuse incidents"],
        required_sections=["Password Requirements", "MFA Requirements", "Privileged Access Rules", "Compliance Monitoring"],
    ),
    DocumentTypeDefinition(
        key="data-retention-policy",
        name="Data Retention and Disposal Policy",
        category="Governance",
        type_code="DRP",
        subtype_code="304",
        description="Policy for data classification, retention periods, archival methods, and secure disposal workflows.",
        common_triggers=["Regulatory update", "Legal guidance", "Storage optimization initiative"],
        required_sections=["Data Categories", "Retention Schedule", "Disposal Standards", "Exception Process"],
    ),
    DocumentTypeDefinition(
        key="vendor-risk-policy",
        name="Vendor Risk Management Policy",
        category="Governance",
        type_code="VRM",
        subtype_code="305",
        description="Defines third-party risk review requirements for onboarding, renewal, and continuous monitoring.",
        common_triggers=["Procurement process update", "Third-party incident", "Compliance control mapping"],
        required_sections=["Risk Tiers", "Due Diligence", "Contract Controls", "Ongoing Monitoring"],
    ),
    DocumentTypeDefinition(
        key="business-continuity-plan",
        name="Business Continuity Plan",
        category="Resilience",
        type_code="BCP",
        subtype_code="306",
        description="Plan for maintaining critical business operations during disruptive events and service interruptions.",
        common_triggers=["Resilience program update", "Merger integration", "Regulatory readiness"],
        required_sections=["Critical Functions", "Continuity Strategies", "Recovery Priorities", "Communication Plan"],
    ),
    DocumentTypeDefinition(
        key="incident-response-policy",
        name="Incident Response Policy",
        category="Governance",
        type_code="IRP",
        subtype_code="307",
        description="Policy-level definition of incident response responsibilities, escalation, and reporting requirements.",
        common_triggers=["SOC operating model update", "Board risk review", "Policy harmonization"],
        required_sections=["Scope", "Severity Model", "Escalation Path", "Post-Incident Requirements"],
    ),
    DocumentTypeDefinition(
        key="standard-operating-procedure",
        name="Standard Operating Procedure",
        category="Operations",
        type_code="SOP",
        subtype_code="401",
        description="Step-by-step procedure for repeatable operational tasks with ownership and validation points.",
        common_triggers=["Process standardization", "Onboarding new staff", "Operational audit"],
        required_sections=["Purpose", "Prerequisites", "Procedure Steps", "Validation", "Escalation"],
    ),
    DocumentTypeDefinition(
        key="service-runbook",
        name="Service Runbook",
        category="Operations",
        type_code="RUN",
        subtype_code="402",
        description="Actionable runbook for incident handling and routine service operations for a specific platform.",
        common_triggers=["Service launch", "Operational handoff", "Major incident lessons learned"],
        required_sections=["Service Overview", "Common Scenarios", "Commands and Actions", "Rollback", "Escalation Contacts"],
    ),
    DocumentTypeDefinition(
        key="problem-record",
        name="Problem Record",
        category="Operations",
        type_code="PRB",
        subtype_code="403",
        description="Tracks recurring incidents and deeper root causes with long-term corrective actions.",
        common_triggers=["Repeat outages", "Recurring alerts", "Trend analysis findings"],
        required_sections=["Problem Statement", "Impact Analysis", "Root Cause Analysis", "Permanent Fix Plan"],
    ),
    DocumentTypeDefinition(
        key="known-error-record",
        name="Known Error Record",
        category="Operations",
        type_code="KER",
        subtype_code="404",
        description="Documents known issues, temporary workarounds, and conditions under which faults may recur.",
        common_triggers=["Root cause not fully remediated", "Interim workaround published", "Service desk guidance update"],
        required_sections=["Error Description", "Symptoms", "Workaround", "Affected Services", "Resolution Plan"],
    ),
    DocumentTypeDefinition(
        key="service-health-report",
        name="Service Health Report",
        category="Operations",
        type_code="SHR",
        subtype_code="405",
        description="Periodic report on service availability, incidents, latency trends, and operational risk indicators.",
        common_triggers=["Weekly ops review", "Executive dashboard", "SLA governance"],
        required_sections=["Availability Metrics", "Incident Summary", "Performance Trends", "Risk Outlook"],
    ),
    DocumentTypeDefinition(
        key="change-request-cab",
        name="Change Request (CAB)",
        category="Change Management",
        type_code="CRQ",
        subtype_code="501",
        description="CAB-ready change request with business impact, implementation plan, test evidence, and rollback.",
        common_triggers=["Production change", "Scheduled release", "Infrastructure modification"],
        required_sections=["Change Description", "Business Impact", "Implementation Steps", "Validation Plan", "Rollback Plan"],
    ),
    DocumentTypeDefinition(
        key="deployment-plan",
        name="Deployment Plan",
        category="Change Management",
        type_code="DPL",
        subtype_code="502",
        description="Detailed deployment sequence for applications or infrastructure changes, including dependencies and timing.",
        common_triggers=["Go-live", "Version release", "Cutover preparation"],
        required_sections=["Scope", "Pre-Deployment Checklist", "Execution Timeline", "Validation", "Fallback"],
    ),
    DocumentTypeDefinition(
        key="rollback-plan",
        name="Rollback Plan",
        category="Change Management",
        type_code="RBP",
        subtype_code="503",
        description="Predefined procedure for reverting changes safely when validation fails or risk thresholds are exceeded.",
        common_triggers=["High-risk change", "Regulated release", "Operational readiness"],
        required_sections=["Rollback Triggers", "Rollback Steps", "Data Considerations", "Verification", "Communication"],
    ),
    DocumentTypeDefinition(
        key="release-notes",
        name="Release Notes",
        category="Change Management",
        type_code="REL",
        subtype_code="504",
        description="Summarizes delivered features, fixes, known issues, and upgrade considerations for a release.",
        common_triggers=["Application release", "Platform update", "Patch rollout"],
        required_sections=["Release Scope", "Enhancements", "Bug Fixes", "Known Issues", "Upgrade Guidance"],
    ),
    DocumentTypeDefinition(
        key="cutover-checklist",
        name="Cutover Checklist",
        category="Change Management",
        type_code="CUT",
        subtype_code="505",
        description="Execution checklist for transition windows with clear owner assignment and completion tracking.",
        common_triggers=["Data center migration", "ERP cutover", "Service transition"],
        required_sections=["Readiness Checks", "Execution Tasks", "Validation Tasks", "Fallback Criteria", "Sign-Off"],
    ),
    DocumentTypeDefinition(
        key="system-design-document",
        name="System Design Document",
        category="Architecture",
        type_code="SDD",
        subtype_code="601",
        description="Technical design for system components, interfaces, constraints, and operational considerations.",
        common_triggers=["New platform build", "Major redesign", "Architecture board review"],
        required_sections=["Design Goals", "Architecture Overview", "Component Design", "Security Considerations", "Operational Model"],
    ),
    DocumentTypeDefinition(
        key="network-topology-document",
        name="Network Topology Document",
        category="Architecture",
        type_code="NTD",
        subtype_code="602",
        description="Captures logical and physical topology, segmentation, addressing, and inter-site connectivity details.",
        common_triggers=["Network refresh", "Merger network integration", "Audit evidence request"],
        required_sections=["Topology Overview", "Addressing Plan", "Segmentation Model", "Interconnects", "Dependencies"],
    ),
    DocumentTypeDefinition(
        key="data-flow-analysis",
        name="Data Flow Analysis",
        category="Architecture",
        type_code="DFA",
        subtype_code="603",
        description="Describes data movement across systems, trust boundaries, and associated security controls.",
        common_triggers=["Privacy assessment", "New integration", "Threat modeling exercise"],
        required_sections=["Data Sources and Destinations", "Flow Paths", "Trust Boundaries", "Control Mapping", "Residual Risks"],
    ),
    DocumentTypeDefinition(
        key="disaster-recovery-test-report",
        name="Disaster Recovery Test Report",
        category="Resilience",
        type_code="DRT",
        subtype_code="604",
        description="Records DR test execution, measured recovery objectives, issues encountered, and remediation tasks.",
        common_triggers=["Annual DR test", "Control validation", "Resilience audit"],
        required_sections=["Test Scope", "RTO and RPO Targets", "Execution Results", "Gaps", "Improvement Actions"],
    ),
    DocumentTypeDefinition(
        key="capacity-planning-report",
        name="Capacity Planning Report",
        category="Architecture",
        type_code="CAP",
        subtype_code="605",
        description="Forecasts infrastructure growth needs and recommends scaling actions based on trend analysis.",
        common_triggers=["Rapid growth period", "Budget planning", "Performance risk review"],
        required_sections=["Current Utilization", "Growth Forecast", "Constraint Analysis", "Capacity Recommendations"],
    ),
    DocumentTypeDefinition(
        key="project-charter",
        name="Project Charter",
        category="Project Delivery",
        type_code="PCH",
        subtype_code="701",
        description="Defines project purpose, scope boundaries, stakeholders, success criteria, and governance model.",
        common_triggers=["Project kickoff", "Funding approval", "Portfolio intake"],
        required_sections=["Objectives", "Scope", "Stakeholders", "Success Criteria", "Governance"],
    ),
    DocumentTypeDefinition(
        key="raid-log-update",
        name="RAID Log Update",
        category="Project Delivery",
        type_code="RAD",
        subtype_code="702",
        description="Structured update of risks, assumptions, issues, dependencies, and mitigation ownership.",
        common_triggers=["Program review", "Steering committee prep", "Project control checkpoint"],
        required_sections=["Risks", "Assumptions", "Issues", "Dependencies", "Action Owners"],
    ),
    DocumentTypeDefinition(
        key="uat-signoff-summary",
        name="UAT Sign-Off Summary",
        category="Project Delivery",
        type_code="UAT",
        subtype_code="703",
        description="Summarizes user acceptance test outcomes, unresolved defects, and formal sign-off status.",
        common_triggers=["Release gate", "Go-live readiness", "Business acceptance review"],
        required_sections=["Test Scope", "Pass-Fail Results", "Open Defects", "Business Approval", "Go-Live Recommendation"],
    ),
    DocumentTypeDefinition(
        key="transition-to-operations",
        name="Transition to Operations",
        category="Project Delivery",
        type_code="TTO",
        subtype_code="704",
        description="Transfers project deliverables into support with operational readiness, ownership, and support procedures.",
        common_triggers=["Project closeout", "Managed service handoff", "Platform onboarding"],
        required_sections=["Delivered Components", "Operational Readiness", "Support Ownership", "Runbooks and SOPs", "Open Risks"],
    ),
]


def list_document_types() -> list[DocumentTypeDefinition]:
    return DOCUMENT_TYPES


def get_document_type(key: str) -> DocumentTypeDefinition:
    for definition in DOCUMENT_TYPES:
        if definition.key == key:
            return definition
    return DOCUMENT_TYPES[0]


def build_document_type_catalog() -> str:
    blocks: list[str] = []
    for item in DOCUMENT_TYPES:
        blocks.append(
            "\n".join(
                [
                    f"Key: {item.key}",
                    f"Name: {item.name}",
                    f"Category: {item.category}",
                    f"Tracking code prefix: {item.type_code}-{item.subtype_code}",
                    f"Description: {item.description}",
                    f"Common triggers: {', '.join(item.common_triggers)}",
                    f"Required sections: {', '.join(item.required_sections)}",
                ]
            )
        )
    return "\n\n".join(blocks)


def build_tracking_code(document_type_key: str, document_date: date) -> str:
    definition = get_document_type(document_type_key)
    date_code = document_date.strftime("%y%m%d")
    return f"{definition.type_code}-{definition.subtype_code}-{date_code}"